export const ActionTypes = {
    SET_ANIMELIST: 'SET_ANIMELIST',
    REMOVE_ANIMELIST: 'REMOVE_ANIMELIST',
    SET_ANIME_DETAIL : 'SET_ANIME_DETAIL',
    REMOVE_ANIME_DETAIL: 'REMOVE_ANIME_DETAIL',
    SET_GENRELIST: 'SET_GENRELIST',
};